### ISSUE TITLE
[Linux] Log files in wrong Folder

### ISSUE THREAD

**Issue by Kiina** [Torndeco/extdb#104]
It seems like the logs belong into "@extDB\extdb\logs" but instead get logged into "@extDB\extDB\logs" because of the case sensitivity on Linux.

**Comment by Torndeco** [comment]
Its meant to be extDB/
Its just the release files have wrong directory case, it prob got mixed up when i redid the release files when i switched over to binary uploads

https://github.com/Torndeco/extdb/blob/stable/src/protocols/db_custom_v5.cpp#L85
https://github.com/Torndeco/extdb/blob/stable/src/protocols/db_custom_v3.cpp#L85

**Comment by Torndeco** [comment]
Fixed the directory names in binary uploads
Thanks for the bug report

**Comment by Kiina** [comment]
Well, thought it was supposed to be changed into "extdb"

**Comment by Torndeco** [comment]
DB Custom files are located inside extDB/
Changing directory case would break anyone that is updating a Server that uses DB_CUSTOM to a newer build.
Try to avoid changes that cause breakage with previous version when i can.

Anyway like i said was just a typo when i was making the new Release Files, since i nuked / remove the old builds from Github.
