### ISSUE TITLE
extDB Development possible hibernation

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extdb#125]
Atm i am considering halting develeopment on extDB, it won't be the first time 

http://forums.bistudio.com/showthread.php?179727-extDB-%28arma3-extension-linux-windows%29&p=2869834&viewfull=1#post2869834

extDB is currently not in use in any active developed public missions / mods
Which means there is very little to no feedback
If you do plan on releasing a public available mod / addon in the near future, please feel free to give me a shout etc...

But mostly likely either i will wait on Arma 2017 release or make up my own Wasteland/KOFH mission that uses extDB.
Regardless i will have a better idea after the weekend, what i will be doing next...

**Comment by LucaDev** [comment]
Please look at http://www.altisliferpg.com/ or http://puu.sh/ffBHB/d2a13d29a3.jpg, I think the Yuka will develop AltisLife from now

**Comment by killerty69** [comment]
We appreciate all the time you have put into it. I will be using extdb for as long as I have my altis life servers up.

**Comment by TDC-Insane** [comment]
I'm using extDB outside AltisLifeRPG or better, I'll use it to set roles (e.g medic, pilots) in our clan internal mission framework.
Also using it in another project..  but therefore no public information :P 

Im currently using DB_Custom_V5, which works really well :)

**Comment by Lict0r** [comment]
Hi,

I am the head developer of Blackwing Gaming (www.blackwing.co.uk). We are a big and popular Altis Life community. I will release a huge update for our mission on friday. This update will include the shift from Arma2Net to extDB.
Our mission is under heavy development and I would be glad to test any new updates on extDB. The release on friday will bring Base Building as a new feature, what no other community offers. All objects are being stored server side in the database. And with all objects, I really mean all. The mission file itself is basically empty. This requires high utilization of a high performance database connection. This is why I decided to switch over to extDB. It would be a shame if you would stop developing on this great tool.

Please contact me if you think that this is a good reason to continue developing on extDB. I will definitely help you to test any new updates.

And btw I started using your awesome pyBEscanner. It already banned 10 script kiddies in only 2 days. I sent you a pull request for a small improvement.

Looking forward to your response.

Cheers, Lictor aka. Joe

**Comment by Torndeco** [comment]
Haven't used pyBEscanner in ages...
Most people have changed to use SQF code to catch hackers, plus using BattlEye scripts.txt isnt performance friendly.

----------------

Anyway i will prob take a break for awhile till whenever Arma 2017 comes out....

I used Linux Dedicated Server that i used for development work, easier to debug issues etc & it is due for renewal in 6 days, think i will just let it expire. 
In entire time for extDB only had a a single donation.

**Comment by killerty69** [comment]
Where can I donate at?

**Comment by Lict0r** [comment]
I'm not using scripts.txt, I'm talking about publicVariable and remoteExec. For example a very common hack contains "toString" which is easy to detect with pyBEscanner. And remoteExec.... well I just ban everything.
And of course we are using in game anti-hack scripts. If you visit those hacking forums like mpgh.net you will find our name in many threads, because we have one of the best developed anti-hack scripts. But there are still some hacks that are hard to detect by SQF only.

If you decide to continue developing on extDB my community would be glad to cover your server costs and do some donations to honour your work. I really like your work and we could work together in the future if your interested.

Let me know what you think.

**Comment by Torndeco** [comment]
If you want to Donate Link is 
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Added it to ReadMe, was previous in Arma Forums Thread.

Server Costs are currently 50 euro a month.
If i manage to get similar amounts, i will keep up the server & continue work on extDB, maybe update pyBEscanner (didnt know people still used it).

Its just hard to justify the cost atm, when i am using server just for extDB develeopment atm
If you do Donate to help pay for costs, please put in something in were you would like to see me work on / improve.

---------------

Don't forget its a Donation Only.
The work is mixture of open-source licenses so you are free to fork the codebase etc. 
Also i am  more than likely restart development whenever Arma 2017 gets released.

So you aren't required to Donate, before anyone complains...

**Comment by killerty69** [comment]
I honestly didn't even see the donate button. I am going to post it around on some forums asking people to donate if that is ok. A lot of people appreciate the work you do, you are just hidden in the background. 

I understand it is a donation, and I am not expecting anything from you for it. I was trying to find a way to send some money your way before because I didn't see the donation option. All I want to do is say thanks even if you stop working on it. I finally got it set up a few days ago so I can start adding some stuff to the code base. Also we need some documentation on the 4:x (single message return), which has been better on my server performance. 

I sent over the donation, please let me know if you don't get enough to cover server cost for the month, I will gladly pay it.

**Comment by ArMaTeC** [comment]
love sent

**Comment by Torndeco** [comment]
Development continued @ https://github.com/Torndeco/extdb2
